### ISSUE TITLE
Benchmark

### ISSUE THREAD

**Issue by cup** [cmuratori/meow_hash#1]
from http://mollyrocket.com/meowhash:

> It’s the fastest hash function we know of by a factor of at least 3.

ok that is great - but what are we comparing it against

would be nice to see what the competitors are and/or what the methodology was

thanks

**Comment by cup** [comment]
@pjanx Meow is a Non-cryptographic hash function, so SipHash is not comparable

http://wikipedia.org/wiki/List_of_hash_functions#Non-cryptographic_hash_functions

**Comment by pjanx** [comment]
@cup It is still a hash function and up for comparison, if only for curiosity reasons.

**Comment by cup** [comment]
@pjanx no, its not. a sensible list would include non-crypto functions, and popular crypto functions - SipHash is neither.

**Comment by cmuratori** [comment]
SipHash is not a fast hash function, so it's not a particularly useful datapoint.  Their "faster version of SipHash" is HighwayHash and it is only 4 bytes per cycle.  Meow hash is 16 bytes per cycle, or roughly 4 times faster in cache.  Out of cache, Meow still wins, but it gets slowed down to memory throughput speed, which varies per CPU so it's hard to quote a particular number.  Modern CPUs can usually deliver memory faster than 4 bytes per cycle, though, so Meow typically still beats 4bpc hashes like Highway et al.

**Comment by cup** [comment]
here are some that might be worth comparing


- http://github.com/google/highwayhash
- http://github.com/jandrewrogers/MetroHash
- http://github.com/lemire/rollinghashcpp
- http://github.com/leo-yuriev/t1ha

**Comment by cup** [comment]
https://github.com/jandrewrogers/MetroHash/issues/7

**Comment by cup** [comment]
https://github.com/lemire/rollinghashcpp/issues/9

**Comment by cup** [comment]
https://github.com/cmuratori/meow_hash/issues/1
https://github.com/jandrewrogers/MetroHash/issues/7
https://github.com/lemire/rollinghashcpp/issues/9

**Comment by cmuratori** [comment]
Really not sure what you're asking for here, because all of these hashes post statistics, as does Meow.  But to summarize, Meow is much faster than everything you posted, _and_ it generates larger hashes as well.  In most cases you can tell that just from reading the web pages you posted :)  Again, Meow is 16 bytes/cycle for up to 512-bit hash.  The hashes you posted all generate smaller hashes at less bytes per cycle.  How much slower they are depends on how big of a hash you ask them to make, because most of them get slower for larger hash outputs, while Meow does not (it is the same speed for any hash size up to 512 bits).

**Comment by cup** [comment]
https://github.com/rurban/smhasher/issues/28
