### ISSUE TITLE
Possible to operate on an input stream rather than a fixed size buffer?

### ISSUE THREAD

**Issue by tim-rex** [cmuratori/meow_hash#2]
This is pretty great. I already have a use case for this that I'd like to explore.

How would the algorithm lend itself to operating on an input stream, where the total buffer size may not be known up front?

Would it be possible to split the input source into fixed-size chunks and then combine the resulting hashes in some way that would yield correct results?

**Comment by cmuratori** [comment]
Yes.  There are two phases to Meow hash, as you can see from the source code (meow_hash.h).  The first phase hashes blocks, and can be done in a streaming fashion if you would like.  You would just cut that part out and call it separately every time you had a new full block.  Then at the end, you would call the final part that hashes a partial block and does the bit mixing.

**Comment by ratchetfreak** [comment]
The main while loop doing the processing starts at line 175.

You can easily split the function up so that the final processing mixing the lanes doesn't happen until it's done and the 5 meow_lanes  that persist (IV+4 being processed) are kept in a struct passed by pointer.

Dealing with the residuals of the input buffer will be the messier part.

**Comment by tim-rex** [comment]
So after a little more investigating, it turns out the codebase I want to integrate this into may actually know the input size up front anyway.. and more surprisingly, as a single contiguous buffer.

In short, while this issue may present a valid use case... it's not currently one that I need to address.

Thank you gentlemen.

**Comment by cmuratori** [comment]
I am testing a version of Meow that only uses the IV at the _end_ (kind of not an IV anymore, but hey :), so I think we may be able to support unknown size hashing anyway.  Thanks for bringing it up!

**Comment by james7132** [comment]
I am starting a python binding for meow_hash. In an attempt to be available as a drop in replacement to the built in Python hashlib APIs, I've whipped up said separated parts of the code: https://github.com/james7132/py-meowhash/blob/master/meowhash/meow_hash.h.

I am also planning on using it in a stream based environment where the length of the incoming stream may be indeterminate. An update to the algorithm such that it doesn't need the length upfront would be highly appreciated.

**Comment by james7132** [comment]
With this change  in mind, what is the timeline before we freeze the algorithm with a definitive version? Such that it would be safe to use across multiple projects/systems consistently for the indefinite future?

(Might be worth to put in a different issue).

**Comment by cmuratori** [comment]
I would like to request open comment on v0.2, which should drop tomorrow.
If there are no major issues, I will bump that to 0.9 beta and consider the
algorithm locked for wide testing.  If no issues are found, then that's 1.0
permanent.

I will likely drop the hash size down to 128 bits, because I don't think
the extra bits are actually guranteed to be anything more unique than the
first 128 right now and they slow things down for no benefit.  So in the
future, if the algorithm is revised, I can make that a different hash that
will be 256 or 512 bits designed for the VAES explicitly, and the 128-bit
version can remain unchanged.

That's my current plan.

**Comment by cmuratori** [comment]
As of v0.2, which is now available, the seed and length are no longer used until the end of the hash, so it should be possible to make streaming constructions now, as necessary.

\- Casey
