### ISSUE TITLE
How much do you expect to change until version 1.0?

### ISSUE THREAD

**Issue by mmcloughlin** [cmuratori/meow_hash#29]
If you don't know the answer to this, no problem at all.

I'm maintaining a [Golang version of Meow hash](https://github.com/mmcloughlin/meow), and wondering whether I should take the effort to stay in sync, or hold off and wait for the dust to settle?

**Comment by cmuratori** [comment]
I would wait for the dust to settle, just because I don't know that there's much reason to have other-language versions of various Meow candidate hashes unless you want to test with them and provide feed back on the function.  At least until v0.4 you can expect the function to change at least slightly with each revision.

\- Casey

**Comment by mmcloughlin** [comment]
Great, that's useful context :)
