### ISSUE TITLE
Is there any way to make compilers execute a proper rdtsc (or rdtscp)?

### ISSUE THREAD

**Issue by cmuratori** [cmuratori/meow_hash#31]
So, I would like to improve the accuracy of meow_bench, and among other things I am doing, I would like to try to get the rdtsc's to behave properly.  In ASM, you can do some fanciness where you set up a dependency chain to force the rdtsc to happen more accurately, but I don't know if there's any modern compiler gyrations you can do to make CLANG or MSVC output something usable here.  Anyone have any ideas?  I don't think MSVC supports inline assembly anymore, but on CLANG maybe it would work to just use inline assembler...

\- Casey

**Comment by mmozeiko** [comment]
Intel recommends following:
```
CPUID
RDTSC
... // benchmarking code
RDTSCP
CPUID
```

Page 16, "The Improved Benchmarking Method" from [How to Benchmark Code Execution Times on Intel® IA-32 and IA-64 Instruction Set Architectures](https://www.intel.com/content/dam/www/public/us/en/documents/white-papers/ia-32-ia-64-benchmark-code-execution-paper.pdf)

In C it would look something like this:
```
    int c[4];
    uint32_t x;
    __cpuid(c, 0);
    uint64_t t0 = __rdtsc();
    ... // DO THE BENCHMARK HERE;
    uint64_t t1 = __rdtscp(&x);
    __cpuid(c, 0);
    uint64_t delta = t1 - t0; 
```
MSVC will not optimize __cpuid away even if you don't use result (c variable), because this is special instruction.

In GCC/CLANG cpuid intrinsic is a bit different, and it is a bit broken in a sense that it can be optimized away if you don't use results from it. Probably doing inline asm in this case makes more sense.

Here's example dissasembly for MSVC and gcc/clang with method Intel suggests: https://godbolt.org/z/j2ioKH

Note that inline asm for non-MSVC case will **not work** for position-independent code. As long as you don't use this code in .so files, it will be fine. Otherwise it needs to be updated to preserve ebx/rbx register.

Not sure what to do if CPU does not support RDTSCP. Fall back to RDTSC (allow user to choose compile time)?

**Comment by cmuratori** [comment]
I don't care if the benchmark doesn't run on non-RDTSCP platforms, that's not really an issue we would care about.  If the _hash_ didn't, maybe that's bad, because eventually we'll want a C path that runs everywhere, etc.  But if the _benchmark_ doesn't, that's fine :)  So I'll throw the CPUIDs in there.

\- Casey

**Comment by cmuratori** [comment]
I've rolled this into the latest v0.3, which I'll update soon.  Thanks Martins!

\- Casey
