### ISSUE TITLE
Consider using -mavx rather than -mavx2 in build.sh's build of meow_bench

### ISSUE THREAD

**Issue by adamdmoss** [cmuratori/meow_hash#69]
-mavx -maes is fine on both Linux/clang++ and Linux/gcc++.
-mavx2 doesn't seem to actually emit avx2-specific code on clang8, or meow_bench is getting lucky. :)
But -mavx2 prompts GCC to emit code that genuinely needs avx2 (and will crash on avx1-only), which seems surplus to the requirements of the actual meowhash implementation.

**Comment by cmuratori** [comment]
We cannot use -mavx for meow_bench because if you want to actually benchmark against other hashes (which we ourselves always do), some of them do not get optimal performance without -mavx2.  The requirements for Meow Bench will only get more stringent, since we will release newer, more modern optimizations of Meow Hash over time, and Meow Bench is for testing the fastest possible path.

\- Casey
